[build-system]
requires = ['setuptools', 'wheel']

[tool.pytest.ini_options]
testpaths = ["./tests"]

[tool.ruff]
select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "I",  # isort
]

[tool.ruff.isort]
force-single-line = true
