[build-system]
requires = ['setuptools', 'wheel']

[tool.pytest.ini_options]
testpaths = ["./tests"]

[tool.isort]
profile = "black"
# Place each import on its own line to reduce merge conflicts
force_single_line = true
