name: Test

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - uses: astral-sh/ruff-action@v3
      - name: Install dependencies
        run: uv sync --all-extras --all-groups
      - name: Check formatting
        run: ruff format --check .
      - name: Lint
        run: ruff check .

  test:
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        os: [ ubuntu-latest ]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        include:
          - os: ubuntu-22.04
            python-version: "3.7"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-python-prereleases: true
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --all-groups

      - name: Run tests
        run: |
          uv run -v --no-sync pytest --cov-report term-missing --cov-report xml --cov=docopt --mypy

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          name: Python ${{ matrix.python-version }}
          fail_ci_if_error: true

      - name: Build wheels and sdist
        run: |
          uv build

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          # These are pure-python, so we don't need to worry about platform
          name: wheels-${{ matrix.python-version }}
          path: |
            dist/*.whl
            dist/*.tar.gz
  release:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: wheels
          path: dist

      - name: Upload packages to Jazzband
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: jazzband
          password: ${{ secrets.JAZZBAND_RELEASE_KEY }}
          repository_url: https://jazzband.co/projects/docopt-ng/upload
